name: Dependency Between Jobs

on: [push]

jobs:
  first:
    name: First Job
    runs-on: ubuntu-latest

    steps:
      - name: Echo First Job
        run: echo "First Job Executed"
  second:
    name: Second Job
    runs-on: ubuntu-latest
    needs: first

    steps:
      - name: Echo Second Job
        run: echo "Second Job Executed"
